
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghxjmumnzvzjfmdqjcmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoeGptdW1uenZ6amZtZHFqY212Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMzA1NjgsImV4cCI6MjA1NzYwNjU2OH0.ycCIqPU5bUXmdu01ykARY_lMi0lTmSczfk922bU4xLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
